//HintName: MinimalApiMapper.JsonContext.g.cs
// <auto-generated/>
#nullable enable
using global::MyTestApi.Groups;
using System.Text.Json.Serialization;

namespace MinimalApiMapper.Generated;

[JsonSerializable(typeof(global::MyTestApi.Groups.TestDto))]
internal partial class MinimalApiMapperJsonContext : JsonSerializerContext
{ }
