//HintName: MinimalApiMapper.ServiceExtensions.g.cs
// <auto-generated/>
#nullable enable
using Microsoft.Extensions.DependencyInjection;

namespace MinimalApiMapper.Generated;

public static class MinimalApiMapperServiceExtensions
{
    public static IServiceCollection AddApiGroups(this IServiceCollection services)
    {
        services.AddScoped<global::MyTestApi.Groups.TestApiGroup>();
        return services;
    }
}
