//HintName: MinimalApiMapper.JsonExtensions.g.cs
// <auto-generated/>
#nullable enable
using Microsoft.Extensions.DependencyInjection;
using Microsoft.AspNetCore.Http.Json;
using System.Text.Json.Serialization;

namespace MinimalApiMapper.Generated;

public static class MinimalApiMapperJsonExtensions
{
    /// <summary>
    /// Configures System.Text.Json serialization options to use the generated MinimalApiMapperJsonContext
    /// containing types discovered in MinimalApiMapper endpoints for Native AOT compatibility.
    /// </summary>
    public static IServiceCollection AddApiGroupSerializers(this IServiceCollection services)
    {
        services.Configure<JsonOptions>(options =>
        {
            options.SerializerOptions.TypeInfoResolverChain.Add(MinimalApiMapperJsonContext.Default);
        });
        return services;
    }
}
